# Generated by Django 5.1.3 on 2025-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_newslettersubscription_status_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
