# Generated by Django 5.1.3 on 2025-04-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_order_checkout_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('serves', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
